"""Export a standalone, synthesizable top.v using the same triangle mesh as Studio."""
import json
import math
from pathlib import Path
import shutil

MAX_BOARD_COMMANDS=8192


def export_top(mesh,project,output=None):
    project=Path(project).resolve()
    output=Path(output or project/'out/image_export').resolve()
    commands=[(0,0,639,0,639,479,0,0,0),(0,0,639,479,0,479,0,0,0)]
    commands += [tuple(t.values) for t in mesh.triangles]
    if len(commands)>MAX_BOARD_COMMANDS:
        raise ValueError(f'上板导出最多支持 {MAX_BOARD_COMMANDS-2:,} 个图片三角形；当前 {len(mesh.triangles):,} 个。请降低三角形上限后重新生成。仿真仍支持更大场景。')
    source=(project/'MGPU.srcs/sources_1/new/top.v').read_text(encoding='utf-8')
    prefix=source[:source.index('    // The generated ROM contains')]
    prefix=prefix.replace('logo -> alignment target -> low-poly space painting -> orbiting satellite.',
                          'draw the exported Image Studio picture, then hold until reset.')
    start=source.index('    mgpu u_mgpu (')
    instance=source[start:source.index('\nendmodule',start)+len('\nendmodule')]
    bits=max(1,(len(commands)-1).bit_length())
    body=f'''    // Generated by Image Studio. Payload is {{x0,y0,x1,y1,x2,y2,c0,c1,c2}}.
    // Commands are triangles, not framebuffer pixels. All rendering uses mgpu.
    localparam FETCH=0,LOAD=1,ISSUE=2,WAIT_GPU=3,ADVANCE=4,HOLD=5;
    reg [2:0] demo_state;
    reg [{bits-1}:0] command_address;
    reg [83:0] command_data;
    (* rom_style="block" *) reg [83:0] commands [0:{len(commands)-1}];
    reg demo_start,saw_busy;
    reg [12:0] drain_count;
    wire gpu_busy,gpu_done;
    reg [9:0] gpu_x0,gpu_y0,gpu_x1,gpu_y1,gpu_x2,gpu_y2;
    reg [7:0] gpu_c0,gpu_c1,gpu_c2;
    // Read-only observation signals keep the shared top_tb compatible.
    wire logo_active=1'b0;
    wire [1:0] scene=2'd1;
    wire [4:0] animation_frame=0;
    wire studio_mode=1'b1;
    wire studio_finished=(demo_state==HOLD);
    always @(posedge gpu_clk) command_data<=commands[command_address];
    always @(posedge gpu_clk) begin
        if(rst) begin
            command_address<=0;demo_state<=FETCH;demo_start<=0;saw_busy<=0;drain_count<=0;
            gpu_x0<=0;gpu_y0<=0;gpu_x1<=0;gpu_y1<=0;gpu_x2<=0;gpu_y2<=0;
            gpu_c0<=0;gpu_c1<=0;gpu_c2<=0;
        end else begin
            demo_start<=0;
            case(demo_state)
                FETCH: demo_state<=LOAD;
                LOAD: begin
                    {{gpu_x0,gpu_y0,gpu_x1,gpu_y1,gpu_x2,gpu_y2,gpu_c0,gpu_c1,gpu_c2}}<=command_data;
                    demo_state<=ISSUE;
                end
                ISSUE: begin demo_start<=1;saw_busy<=0;drain_count<=0;demo_state<=WAIT_GPU;end
                WAIT_GPU: begin
                    if(gpu_busy) begin saw_busy<=1;drain_count<=0;end
                    else if(saw_busy) drain_count<=drain_count+1'b1;
                    if(saw_busy && (gpu_done || (!gpu_busy && &drain_count))) demo_state<=ADVANCE;
                end
                ADVANCE: begin
                    if(command_address=={len(commands)-1}) demo_state<=HOLD;
                    else begin command_address<=command_address+1'b1;demo_state<=FETCH;end
                end
                HOLD: demo_state<=HOLD;
                default: demo_state<=FETCH;
            endcase
        end
    end
    initial begin
'''
    for i,command in enumerate(commands):
        word=0
        for j,value in enumerate(command):word=(word << (10 if j<6 else 8)) | value
        body+=f"        commands[{i}]=84'h{word:021x};\n"
    body+='    end\n'
    output.mkdir(parents=True,exist_ok=True)
    (output/'top.v').write_text(prefix+body+instance+'\n',encoding='utf-8')
    rtl=output/'rtl';rtl.mkdir(exist_ok=True)
    for file in (project/'MGPU.srcs/sources_1/new').glob('*.v'):
        if file.name!='top.v':shutil.copy2(file,rtl/file.name)
    shutil.copy2(project/'MGPU.srcs/constrs_1/new/nexys_a7_vga.xdc',output/'nexys_a7_vga.xdc')
    (output/'build.tcl').write_text('''set root [file dirname [file normalize [info script]]]
cd $root
read_verilog [glob [file join $root rtl *.v]]
read_verilog [file join $root top.v]
read_xdc [file join $root nexys_a7_vga.xdc]
synth_design -top top -part xc7a100tcsg324-1
opt_design
place_design
phys_opt_design
route_design
report_timing_summary -file timing.rpt
report_utilization -file utilization.rpt
report_drc -file drc.rpt
foreach kind {max min} {
    set path [get_timing_paths -delay_type $kind -max_paths 1]
    if {[llength $path]==0 || [get_property SLACK $path]<0} {error "Timing failed"}
}
write_bitstream -force image_top.bit
''',encoding='utf-8')
    metadata=dict(top='top',image_triangles=len(mesh.triangles),commands=len(commands),
                  rom_bits=84*len(commands),rom_bram36_upper_bound=3*math.ceil(len(commands)/1024),
                  gpu_mhz=6.25,hardware_limit=MAX_BOARD_COMMANDS)
    (output/'manifest.json').write_text(json.dumps(metadata,indent=2),encoding='utf-8')
    (output/'README.txt').write_text('''Image Studio 上板包：目标 Nexys A7-100T，RGB332。
top.v 是综合顶层，rtl/ 是原 GPU/VGA 的副本，nexys_a7_vga.xdc 是板级约束。
运行 vivado -mode batch -source build.tcl 生成 image_top.bit；每个新图片仍须通过布局布线时序检查。
也可在独立 Vivado 工程中加入这些文件并把 top 设为顶层。不要同时加入原工程的另一个 top.v。
复位后先清屏，再绘制图片，完成后一直显示；CPU_RESETN 可重画。
此目录不会替换原工程的 Logo/卫星演示。不要手改数字表，修改图片后重新导出。
''',encoding='utf-8')
    return output/'top.v'
