#!/usr/bin/env python3
"""
View a 640x480 RGB332 framebuffer exported by mgpu_tb.v.

Expected input format:
    One hex byte per line, total 640*480 lines.

Example:
    python tools/view_framebuffer.py out/framebuffer.hex

The script always writes:
    out/framebuffer.png

If Pillow is installed, it uses Pillow. Otherwise it writes a plain PPM file,
which many image viewers can open.
"""

from __future__ import annotations

import argparse
from pathlib import Path


WIDTH = 640
HEIGHT = 480
PIXELS = WIDTH * HEIGHT


def rgb332_to_rgb888(value: int) -> tuple[int, int, int]:
    """Convert one RGB332 byte into a normal 24-bit RGB tuple."""
    red_3bit = (value >> 5) & 0x07
    green_3bit = (value >> 2) & 0x07
    blue_2bit = value & 0x03

    red = red_3bit * 255 // 7
    green = green_3bit * 255 // 7
    blue = blue_2bit * 255 // 3
    return red, green, blue


def read_hex_framebuffer(path: Path) -> list[int]:
    pixels: list[int] = []

    with path.open("r", encoding="ascii") as file:
        for line_number, line in enumerate(file, start=1):
            text = line.strip()
            if not text:
                continue

            try:
                value = int(text, 16)
            except ValueError as exc:
                raise ValueError(f"Invalid hex byte at line {line_number}: {text!r}") from exc

            if value < 0 or value > 0xFF:
                raise ValueError(f"Value out of byte range at line {line_number}: {text!r}")

            pixels.append(value)

    if len(pixels) != PIXELS:
        raise ValueError(f"Expected {PIXELS} pixels, got {len(pixels)}")

    return pixels


def save_with_pillow(rgb_pixels: list[tuple[int, int, int]], output_png: Path) -> bool:
    try:
        from PIL import Image
    except ImportError:
        return False

    image = Image.new("RGB", (WIDTH, HEIGHT))
    image.putdata(rgb_pixels)
    image.save(output_png)
    return True


def save_as_ppm(rgb_pixels: list[tuple[int, int, int]], output_ppm: Path) -> None:
    # PPM P6 is a tiny binary image format:
    #   header: P6 <width> <height> 255
    #   payload: raw RGB bytes
    with output_ppm.open("wb") as file:
        file.write(f"P6\n{WIDTH} {HEIGHT}\n255\n".encode("ascii"))
        for red, green, blue in rgb_pixels:
            file.write(bytes((red, green, blue)))


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert MGPU framebuffer.hex to an image.")
    parser.add_argument(
        "framebuffer",
        nargs="?",
        default="out/framebuffer.hex",
        help="Path to framebuffer.hex generated by mgpu_tb.v",
    )
    args = parser.parse_args()

    framebuffer_path = Path(args.framebuffer)
    output_dir = Path("out")
    output_dir.mkdir(exist_ok=True)

    raw_pixels = read_hex_framebuffer(framebuffer_path)
    rgb_pixels = [rgb332_to_rgb888(value) for value in raw_pixels]

    output_png = output_dir / "framebuffer.png"
    output_ppm = output_dir / "framebuffer.ppm"

    if save_with_pillow(rgb_pixels, output_png):
        print(f"Wrote {output_png}")
    else:
        save_as_ppm(rgb_pixels, output_ppm)
        print("Pillow is not installed, so PNG output was skipped.")
        print(f"Wrote {output_ppm}")
        print("Install Pillow with: python -m pip install pillow")


if __name__ == "__main__":
    main()
